<?php

namespace App\Imports;

use App\Models\Building;
use Maatwebsite\Excel\Concerns\ToModel;

class BuildingsImport implements ToModel
{
    /**
    * @param array $row
    *
    * @return \Illuminate\Database\Eloquent\Model|null
    */
    public function model(array $row)
    {
        return new Building([
            'areas_id'    => $row[0],
            'bbns_id'    => $row[1],
            'area3bb_id'    => $row[2],
            'areaAis_id'    => $row[3],
            'areaTrue_id'    => $row[4],
            'areaTrueNew_id'    => $row[5],
            'areaFibernet_id'    => $row[6],
            'areaTxrx_id'    => $row[7],
            'areaSyphony_id'    => $row[8],
            'contractTerm_id'    => $row[9],
            'projectName'    => $row[10],
            'subBuildingsum'    => $row[11],
            'floorSum'    => $row[12],
            'roomSum'    => $row[13],
            'nameNiti'    => $row[14],
            'phoneNiti'    => $row[15],
            'mailNiti'    => $row[16],
            'houseNumber'    => $row[17],
            'squadNumber'    => $row[18],
            'alleyName'    => $row[19],
            'roadName'    => $row[20],
            'districtName'    => $row[21],
            'provinceName'    => $row[22],
            'countyName'    => $row[23],
            'postalCode'    => $row[24],
            'latitude'    => $row[25],
            'longitude'    => $row[26],
            'contractStartDate'    => $row[27],
            'paymentType_id'    => $row[28],
            'saleFm_id'    => $row[29],
            'contractEndDate'    => $row[30],
            'balance'    => $row[31],
            'remarkContract'    => $row[32],
            'workTime_id'    => $row[33],
            'remark'    => $row[34],
            'spendSpace'    => $row[35],
            // 'areas_id'     => $row['areas_id'],
            // 'bbns_id'    => $row['bbns_id'],
            // 'area3bb_id'    => $row['area3bb_id'],
            // 'areaAis_id'    => $row['areaAis_id'],
            // 'areaTrue_id'    => $row['areaTrue_id'],
            // 'areaTrueNew_id'    => $row['areaTrueNew_id'],
            // 'areaFibernet_id'    => $row['areaFibernet_id'],
            // 'areaTxrx_id'    => $row['areaTxrx_id'],
            // 'areaSyphony_id'    => $row['areaSyphony_id'],
            // 'contractTerm_id'    => $row['contractTerm_id'],
            // 'projectName'    => $row['projectName'],
            // 'subBuildingsum'    => $row['subBuildingsum'],
            // 'floorSum'    => $row['floorSum'],
            // 'roomSum'    => $row['roomSum'],
            // 'nameNiti'    => $row['nameNiti'],
            // 'phoneNiti'    => $row['phoneNiti'],
            // 'mailNiti'    => $row['mailNiti'],
            // 'houseNumber'    => $row['houseNumber'],
            // 'squadNumber'    => $row['squadNumber'],
            // 'alleyName'    => $row['alleyName'],
            // 'roadName'    => $row['roadName'],
            // 'districtName'    => $row['districtName'],
            // 'provinceName'    => $row['provinceName'],
            // 'countyName'    => $row['countyName'],
            // 'postalCode'    => $row['postalCode'],
            // 'latitude'    => $row['latitude'],
            // 'longitude'    => $row['longitude'],
            // 'contractStartDate'    => $row['contractStartDate'],
            // 'paymentType_id'    => $row['paymentType_id'],
            // 'saleFm_id'    => $row['saleFm_id'],
            // 'contractEndDate'    => $row['contractEndDate'],
            // 'balance'    => $row['balance'],
            // 'remarkContract'    => $row['remarkContract'],
            // 'workTime_id'    => $row['workTime_id'],
            // 'remark'    => $row['remark'],
            // 'spendSpace'    => $row['spendSpace'],

        ]);
    }
}
//          'areas_id'    => $row[0],
            // 'bbns_id'    => $row[1],
            // 'area3bb_id'    => $row[2],
            // 'areaAis_id'    => $row[3],
            // 'areaTrue_id'    => $row[4],
            // 'areaTrueNew_id'    => $row[5],
            // 'areaFibernet_id'    => $row[6],
            // 'areaTxrx_id'    => $row[7],
            // 'areaSyphony_id'    => $row[8],
            // 'contractTerm_id'    => $row[9],
            // 'projectName'    => $row[10],
            // 'subBuildingsum'    => $row[11],
            // 'floorSum'    => $row[12],
            // 'roomSum'    => $row[13],
            // 'nameNiti'    => $row[14],
            // 'phoneNiti'    => $row[15],
            // 'mailNiti'    => $row[16],
            // 'houseNumber'    => $row[17],
            // 'squadNumber'    => $row[18],
            // 'alleyName'    => $row[19],
            // 'roadName'    => $row[20],
            // 'districtName'    => $row[21],
            // 'provinceName'    => $row[22],
            // 'countyName'    => $row[23],
            // 'postalCode'    => $row[24],
            // 'latitude'    => $row[25],
            // 'longitude'    => $row[26],
            // 'contractStartDate'    => $row[27],
            // 'paymentType_id'    => $row[28],
            // 'saleFm_id'    => $row[29],
            // 'contractEndDate'    => $row[30],
            // 'balance'    => $row[31],
            // 'remarkContract'    => $row[32],
            // 'workTime_id'    => $row[33],
            // 'remark'    => $row[34],
            // 'spendSpace'    => $row[35],


            